# Generated by Django 4.1.6 on 2023-02-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoute',
            new_name='Quote',
        ),
    ]
